CREATE FUNCTION param1(NUMERIC)
  RETURNS NUMERIC AS $$
SELECT CASE WHEN $1 < 0 THEN 1
            ELSE 1 + param1($1 - 1)
       END
$$ LANGUAGE SQL;

CREATE FUNCTION param2(NUMERIC, NUMERIC)
  RETURNS NUMERIC AS $$
SELECT CASE WHEN $1 < 0 THEN 1
            ELSE 1 + param2($1 - 1, $2)
       END
$$ LANGUAGE SQL;

CREATE FUNCTION param3(NUMERIC, NUMERIC, NUMERIC)
  RETURNS NUMERIC AS $$
SELECT CASE WHEN $1 < 0 THEN 1
            ELSE 1 + param3($1 - 1, $2, $3)
       END
$$ LANGUAGE SQL;

CREATE FUNCTION param4(NUMERIC, NUMERIC, NUMERIC, NUMERIC)
  RETURNS NUMERIC AS $$
SELECT CASE WHEN $1 < 0 THEN 1
            ELSE 1 + param4($1 - 1, $2, $3, $4)
       END
$$ LANGUAGE SQL;